### ISSUE TITLE
Banner is not activated in /etc/ssh/sshd_config

### ISSUE THREAD

**Issue by shponny** [palchyk-alex/lab01#3]
Согласно [вики](https://wiki.centos.org/TipsAndTricks/BannerFiles) centos, `banner` по умолчанию не активен, его нужно активировать в `/etc/ssh/sshd_config`, а потом перезагрузить `sshd`.

**Comment by palchyk-alex** [comment]
Activated it in #5 . Thanks for pointing, I'll close issue when pull request gets approved. @shponny
